src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantApplicantDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantApplicantController.java

Added email field to GrantApplicantDto and GrantApplicantController

GAP-1993: Old JWT values amended

---

src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java

Addresses GAP 2226 by aligning the JSON blob definition for submissions with attachments to the cleaned filename shown in S3

Cleaned filename wherever getOriginalFilename is called

---

src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java

Adds : to the filename cleanup

Added : to the cleaning of filenames

---

pom.xml
src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantMandatoryQuestionDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/mapper/GrantApplicantOrganisationProfileMapper.java
src/main/java/gov/cabinetoffice/gap/applybackend/mapper/GrantMandatoryQuestionMapper.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
src/test/java/gov/cabinetoffice/gap/applybackend/mapper/GrantApplicantOrganisationProfileMapperTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/mapper/GrantMandatoryQuestionMapperTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsControllerTest.java

change redirection logic,
updates Dtos
add mapStruct

Tmi2 331/mandatory question entry point

---

src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantAdvertDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/mapper/GrantMandatoryQuestionMapper.java
src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantApplication.java
src/main/java/gov/cabinetoffice/gap/applybackend/repository/GrantAdvertRepository.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertController.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertControllerTest.java

add endpoint to get an advert by scheme id, refactor, and add test coverage

Tmi2 412/add action on mandatory question summary page

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java

to determine the status of the submission button we were only checking that all the mandatory question in each section were answered. 
now we also check that the status of the section is completed

update logic for disabling the submission button

---

src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/UpdateGrantApplicantOrganisationProfileDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/UpdateGrantMandatoryQuestionDto.java

Tmi2 433/update validation for mand questions companies and charity number

---

src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/UpdateGrantMandatoryQuestionDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsControllerTest.java

Added code to handle the inclusion of a flag to set the MQ status to complete.

TMI2-428: MQ status is never set to complete

---

src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantMandatoryQuestions.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/utils/GapIdGenerator.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsControllerTest.java

- If a submission exists, it's gap_id is added to MQ table
- If a submission doesn't exist, a  new gap_id is created and added to MQ table

TMI2-335 creating and adding gap_id to mandatory questions

---

src/main/java/gov/cabinetoffice/gap/applybackend/repository/GrantApplicantRepository.java
src/main/java/gov/cabinetoffice/gap/applybackend/security/JwtTokenFilterV2.java
src/main/java/gov/cabinetoffice/gap/applybackend/security/WebSecurityConfig.java

https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2295

GAP-2295: Create new user in middleware if valid jwt but no applicant exists

---

pom.xml
src/main/java/gov/cabinetoffice/gap/applybackend/config/SQSConfig.java
src/main/java/gov/cabinetoffice/gap/applybackend/config/SpotlightQueueConfigProperties.java
src/main/java/gov/cabinetoffice/gap/applybackend/enums/SpotlightBatchStatus.java
src/main/java/gov/cabinetoffice/gap/applybackend/enums/SpotlightSubmissionStatus.java
src/main/java/gov/cabinetoffice/gap/applybackend/model/SpotlightBatch.java
src/main/java/gov/cabinetoffice/gap/applybackend/model/SpotlightSubmission.java
src/main/java/gov/cabinetoffice/gap/applybackend/repository/SpotlightSubmissionRepository.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/SpotlightService.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
src/main/resources/application.properties
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/SpotlightServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java

Description
Adds functionality to send messages to Amazon SQS so that due diligence checks can be automatically performed. 
Story
https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-396
This PR depends on the PR below also being approved and merged: 
https://github.com/cabinetoffice/gap-find-admin-backend/pull/70

TMI2-396: Add submissions to SQS for processing in Spotlight

---

src/main/java/gov/cabinetoffice/gap/applybackend/constants/MandatoryQuestionConstants.java
src/main/java/gov/cabinetoffice/gap/applybackend/enums/GrantApplicantOrganisationType.java
src/main/java/gov/cabinetoffice/gap/applybackend/enums/GrantMandatoryQuestionOrgType.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java

[GAP-2249](https://technologyprogramme.atlassian.net/browse/GAP-2249)
reorder submission questions, conditionally remove questions if individual or non-limited company, conditionally change title if individual
Related PRs:
https://github.com/cabinetoffice/gap-find-apply-web/pull/164
[GAP-2249]: https://technologyprogramme.atlassian.net/browse/GAP-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP-2249: Conditional Logic - Changes to submission for applicant types

---

pull_request_template.md
src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantApplicationDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantSchemeDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantSchemeWithApplicationAndAdverts.java
src/main/java/gov/cabinetoffice/gap/applybackend/mapper/GrantSchemeMapper.java
src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantScheme.java
src/main/java/gov/cabinetoffice/gap/applybackend/repository/GrantSchemeRepository.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantSchemeService.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeController.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantSchemeServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeControllerTest.java

[GAP-2303](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2303)
- Adding PR template
- Adding advert & application relations to grantScheme entity class
- Eagerly fetching advert & application as part of getScheme endpoint
- Mapping relations to DTOs
Doesn't really have any UI change but recording of it working for a scheme with no advert & an application form, and one with an advert & application form:
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/e2f34957-a …

GAP-2303: Eagerly fetching scheme ads & application

---

src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantApplicantOrganisationProfile.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicantOrganisationProfileService.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantApplicantOrganisationProfileController.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicantOrganisationProfileServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantApplicantOrganisationProfileControllerTest.java

Ticket [GAP-2251](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2251)
- Endpoint to determine if an org profile is "complete" or not
Journey with an INCOMPLETE profile:
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/72045111-6ede-4555-9276-91b81c661fca
Journey with a COMPLETE profile:
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/c311e47f-73ce-4a71-9c81-b2bea1d40f3d
[GAP-2251]: …

GAP-2251: Is org profile complete endpoint

---

src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java

Ticket # and link GAP-2257
More whitelisted chars.

GAP-2257 Additional whitelisted chars

---

src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java

[Ticket 2309
](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2309)
- Validation blew up on multiresponse questions due to the response field being null, but char validation expecting it

GAP-2309: Fixing v1 schemes from blowing up

---

src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantApplication.java
src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantScheme.java
src/main/java/gov/cabinetoffice/gap/applybackend/repository/GrantApplicationRepository.java

[Ticket 2311](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2311)
Relationships infinitely recursed before, this fixes the relationship locally.
Concerned this might break in other areas but tested some journeys locally with success.

GAP-2311: Fixing v1 applications

---

src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantMandatoryQuestionDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/mapper/GrantMandatoryQuestionMapper.java
src/test/java/gov/cabinetoffice/gap/applybackend/mapper/GrantMandatoryQuestionMapperTest.java

add status to the dto, and modify the mapper to accomodate it

---

src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantAdvertDto.java

https://technologyprogramme.atlassian.net/browse/TMI2-479
Fix isPublished key not having correct key when being returned in REST call

TMI2-479: Fix isPublished having wrong key in response

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/AttachmentService.java

https://technologyprogramme.atlassian.net/browse/TD-110
Removing a stack trace that was exposed to user-space.

TD-110 - Removing stack trace 

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java

The message within the exception is not seen in cloudwatch - this adds a log above the exception so the logs are easier to parse

Add log before throwing invalid redirect error

---

src/main/java/gov/cabinetoffice/gap/applybackend/config/S3Config.java
src/main/java/gov/cabinetoffice/gap/applybackend/model/Submission.java
src/main/java/gov/cabinetoffice/gap/applybackend/provider/AmazonProvider.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/ZipService.java
src/main/java/gov/cabinetoffice/gap/applybackend/utils/ZipHelper.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/OdtServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/ZipServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/testData/TestData.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java

https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2388
related pr: https://github.com/cabinetoffice/gap-find-apply-web/pull/255

GAP-2388: Download Submission zip

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/ZipService.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java

Use attachment bucket when generating submission export 

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Improvements & fixes for odt submission summary doc

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Final final odt doc style updates (final version) 

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Adds page breaks between sections in the odt summary doc

Add page breaks

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

fix null str check

---

.github/workflows/imageBuild.yml
.github/workflows/promoteToProd.yml

Tmi2 532/run actions as aws role

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Use correct email to gen odt

---

src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java

Fixes a bug with the current getNumberOfWords implementation (it includes additional spaces and new lines when counting words)

Normalize string before validating

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Merging release branch into develop

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Ticket # and link[ GAP-2442](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2442)
Adds a regex to check for custom sections before printing header.
Adds a check for blank date string array.
Small bugfix and minor code cleanup

GAP-2442: Fix ODT structure (Date/Custom Sections)

---

.github/workflows/imageBuild.yml

adding role access to deploy stage

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Remove an unintended pagebreak in odt custom sections

GAP-2442: rm page-break

---

src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsControllerTest.java

TMI2-663: set CHN and CCN as null if orgType of the submission is Local authority, Individual or Other

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java

TMI2-628 - removes charity commission and companies house number from local authority questions

---

src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java

Adds a formatter to the submission date to make it more readable for admins

ODT Date Formatter

---

src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java

fix multi reponse validation logic

---

src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/CreateGrantBeneficiaryDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantBeneficiaryDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantBeneficiary.java
src/main/java/gov/cabinetoffice/gap/applybackend/repository/GrantApplicationRepository.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicationService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertController.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeController.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicationServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertControllerTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeControllerTest.java

* checks scheme version instead of submission version and only returns published adverts
* removed comment
* updated method to check for application status
* replaced null logic with filter

DRAFT: release/10.0

---

src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/SchemeMandatoryQuestionApplicationFormInfosDto.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeController.java
src/main/resources/application.properties
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsControllerTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeControllerTest.java

[GAP-2537](https://technologyprogramme.atlassian.net/browse/GAP-2537)
Updates the logic to handle the Removed status of application form in the mandatory question journey
[GAP-2537]: https://technologyprogramme.atlassian.net/browse/GAP-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP-2537: add logic to handle mandatory questions for internal removed application forms

---

src/main/java/gov/cabinetoffice/gap/applybackend/annotations/LambdasHeaderValidator.java
src/main/java/gov/cabinetoffice/gap/applybackend/config/LambdaSecretConfigProperties.java
src/main/java/gov/cabinetoffice/gap/applybackend/config/LambdasInterceptor.java
src/main/java/gov/cabinetoffice/gap/applybackend/security/interceptors/AuthorizationHeaderInterceptor.java
src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
src/main/resources/application.properties
src/test/java/gov/cabinetoffice/gap/applybackend/security/interceptors/AuthorizationHeaderInterceptorTest.java
src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java

GAP-2594: encrypt-secret-used-by-lambda

---

src/main/java/gov/cabinetoffice/gap/applybackend/security/filters/CustomRequestLoggingFilter.java

GAP-2422: fix logic

---

src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java
src/test/java/gov/cabinetoffice/gap/applybackend/validation/annotations/QuestionResponseValidatorTest.java

GAP-2618: fix date validation

---

src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java
src/test/java/gov/cabinetoffice/gap/applybackend/validation/annotations/QuestionResponseValidatorTest.java

Amends validation for drop down values

---

src/main/java/gov/cabinetoffice/gap/applybackend/enums/GrantMandatoryQuestionFundingLocation.java

added International to enum

---

.github/workflows/imageBuild.yml

upload-artifact updated to v4

---

src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java
src/test/java/gov/cabinetoffice/gap/applybackend/validation/annotations/QuestionResponseValidatorTest.java

International changes
