- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
Background
When a user uploads a file - the question is marked as “Complete”. If the file is removed and a user selects ‘back’. There is no file uploaded to the file upload question, but the section is still marked as “Complete”.
Fix
Call handleSectionReview method to update section state to "IN PROGRESS"
Testing
Updated existing test to verify method is called
JIRA
Fixes https://technologyprogramme.atlassian.net/browse/GAP-1758
> fix(SubmissionController): update section state when attachment is removed

- src/main/java/gov/cabinetoffice/gap/applybackend/exception/UnauthorizedException.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/SecretAuthService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/main/resources/application.properties
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SecretAuthServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
- Adding a secret env value
- Endpoint that lambda calls now expects an Authorization header
- Adding a service that validates this header matches the secret env value
- Throws an UnAuth Exception if it does not match
> Gap 1673/authenticate lambda endpoint

- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
Description of change: 
Added methods to search the entire submission definition fo mandatory question IDs rather than searching within a specified section. This means that if the structure of the mandatory questions changes again in future we won't introduce another breaking change to the code.
Cause: 
The mandatory question information used to live in a section with an ID of `ESSENTIAL` but this has now been split into two new sections and the questions within have been spread across the two. This meant that the code to populate diligence checks and beneficiary information could not find the information it was looking for and was throwing an exception. 
Story: 
https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-425
> TMI2-425: Cannot submit application

- src/main/java/gov/cabinetoffice/gap/applybackend/repository/SubmissionRepository.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
Ticket: https://technologyprogramme.atlassian.net/browse/TMI2-382
Changes create submission behaviour so that if one already exists we return it instead of throwing an error.  The frontend will then redirect appropriately to the submission page.
> fix(submissions): when creating submission return submission if one already exists

- .github/workflows/imageBuild.yml
Now triggers on creation & pushes to develop or release branches
- Annoyingly create cant specify branches, so an additional check is needed per job as per: https://github.com/orgs/community/discussions/26286#discussioncomment-3251208
> Fix trigger CD on push & create

- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
Forgot to fulfil the requirement of checking the organisation type before sending due diligence checks to spotlight so have added that functionality. 
story: 
https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-396
> TMI2-396: Adding an org type check for sending to spotlight

- src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/utils/GapIdGenerator.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
https://technologyprogramme.atlassian.net/browse/TMI2-484
Changed the way GAP IDs are generated. Mandatory Questions will always have a GAP ID assigned when they are completed. When a submission is completed, if it has an attached MQ record (ie a V2 scheme) it will use the GAP ID from that, otherwise it will continue to use the existing generation logic.
Also added an identifier to the GAP ID for which version of the scheme it is.
Also manual testing to ensure downloading required checks works as expected.
> TMI2-484: Fix GAP ID Generation

- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
- Fixed a bug where revisiting the eligibility section and re-submitting the answer as "yes" would reset other section statuses.
> eligibility section bug on v2 schemes

- src/main/java/gov/cabinetoffice/gap/applybackend/config/properties/S3ConfigProperties.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/AttachmentService.java
- src/main/resources/application.properties
[Ticket GAP-2341](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2341)
- Attachments wound up in a different bucket than what our delete endpoint attempts to delete from
- Now deleting from both buckets as it may exist in either depending on when the virus scan lambda processes them
Dependent on:
- https://eu-west-2.console.aws.amazon.com/codesuite/codecommit/repositories/GAP-infra/pull-requests/201/details?region=eu-west-2
> GAP-2341: Cleanup attachments properly

- src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertControllerTest.java
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2349
Adds an endpoint to validate a redirectUrl against the grantWebpageUrl attached to a contentful entry.
related prs: 
user-service: https://github.com/cabinetoffice/gap-user-service/pull/167
Applicant fe: https://github.com/cabinetoffice/gap-find-apply-web/pull/221/files
> GAP-2349: Fix open redirects

- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
Returns true if eligibility section response is 'Yes', otherwise it returns false. This is needed so that the user cannot submit an application if they have selected 'No' for the eligibility section  
TD-150: https://technologyprogramme.atlassian.net/browse/TD-150
> TD-150: returns true or false based on eligibility section response

- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
Changed code to only check the eligibility response if it is not null, otherwise return false.
TMI-523: https://technologyprogramme.atlassian.net/browse/TMI2-523
> TMI2-523: checks eligibility response

- src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetSubmissionDto.java
- src/main/java/gov/cabinetoffice/gap/applybackend/enums/SubmissionStatus.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
[GAP-2095](https://technologyprogramme.atlassian.net/browse/GAP-2095)
Add GRANT_CLOSED status to enum
Return submittedDate as part of submission response for display
[GAP-2095]: https://technologyprogramme.atlassian.net/browse/GAP-2095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2095: add GRANT_CLOSED submission status, return submitted date as part of response

- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
Adds endpoint which allows the middleware to get the status of an application from the submission id for that application.
[GAP-2360](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2360)
This endpoint takes in a submission ID which the middleware provides by parsing the values between /mandatory-questions/{submission-id} and submission/{submission-id}. This lets the middleware reroute the user to the grant-is-closed page when this endpoint returns a REMOVED status half-way through an application
Please attach screenshots of …
> GAP-2360: Add endpoints for middleware

- src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/CreateQuestionResponseDto.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
[GAP-2096](https://technologyprogramme.atlassian.net/browse/GAP-2096)
Needed to add a way to not reset the section status when editing a Custom Section question from the summary screen
https://github.com/cabinetoffice/gap-find-apply-web/pull/234
[GAP-2096]: https://technologyprogramme.atlassian.net/browse/GAP-2096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2096 | conditionally don't reset section status to in progress

- src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsControllerTest.java
Adds endpoint to check an application's status from the a mandatory questions page's UUID
This enables middleware to check if the grant-is-closed between every navigation of mandatory questions
> GAP:2360 Application Status from Mandatory Q UUID

- src/main/java/gov/cabinetoffice/gap/applybackend/service/SecretAuthService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
[Ticket # and link](https://technologyprogramme.atlassian.net/browse/TMI2-667)
an endpoint which is consumed by the lambda-upload was getting the applicant Id from the Security context and then passing it to a service method to filter result based on the applicant Id.
since this endpoint is whitelisted, as we check the authenticity of the call from the lambda in other ways, the Security context is never built, which would lead to this endpoint always throwing an error at the service method.
This pr fixes the issue.
> Tmi2 667/update endpoint consumed by lambda upload

- src/main/java/gov/cabinetoffice/gap/applybackend/constants/MandatoryQuestionConstants.java
- src/main/java/gov/cabinetoffice/gap/applybackend/enums/GrantApplicantOrganisationType.java
- src/main/java/gov/cabinetoffice/gap/applybackend/enums/GrantMandatoryQuestionOrgType.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/SubmissionController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/SubmissionControllerTest.java
[TMI2-628 - Add local authority option for an applicant](https://technologyprogramme.atlassian.net/browse/TMI2-628)
> TMI2-628 - Add local authority to applicant organisation and MQs

- src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java
This change fixes the blank "Not Provided" for optional multi-selects.
Also changes custom section table to 2/3rds layout
> ODT Structure Changes

- src/main/java/gov/cabinetoffice/gap/applybackend/service/OdtService.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/OdtServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/testData/TestData.java
the work done to add local authority as an org type, would break the "review and submit" page, where anapplicants can download their own submissions
> add local authority logic in the odt file generation

- src/main/java/gov/cabinetoffice/gap/applybackend/repository/GrantApplicationRepository.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicationService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertController.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicationServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantMandatoryQuestionServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantAdvertControllerTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeControllerTest.java
It checks the scheme version instead of the submission version inside `addMandatoryQuestionsToSubmissionObject` and 
only adds grant adverts to `grantAdvertDtos` list if it has a status of PUBLISHED
TMI2-697: https://technologyprogramme.atlassian.net/browse/TMI2-697
> TMI2-697: handle draft adverts

- src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/CreateGrantBeneficiaryDto.java
- src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/GetGrantBeneficiaryDto.java
- src/main/java/gov/cabinetoffice/gap/applybackend/model/GrantBeneficiary.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/SubmissionService.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/SubmissionServiceTest.java
[Ticket # and link](https://technologyprogramme.atlassian.net/browse/TMI2-740)
Fixing issue where locations "outside of Uk" and "London" were not saving to the grant_beneficiary table on application submission.
> Adding handling for grant beneficiary locations "outside uk" and "london"

- src/main/java/gov/cabinetoffice/gap/applybackend/validation/validators/QuestionResponseValidator.java
[TMI2-732](https://technologyprogramme.atlassian.net/browse/TMI2-732?atlOrigin=eyJpIjoiZTQzZGZmNDRkNTY5NGRjMjlhNGY2ZDM1MTU2MmU1Y2MiLCJwIjoiaiJ9)
As per the ticket, this PR involves adding a fix allowing for use of formatted single and double quotation marks that are often used when copying text from word documents.
Please attach screenshots of the change if it is a UI chPlease attach screenshots of the change if it is a UI change:ange:
[TMI2-732]: https://technologyprogramme.atlassian.net/browse/TMI2-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TMI2-732: Single and double quotation marks fix

- src/main/java/gov/cabinetoffice/gap/applybackend/web/controlleradvice/ControllerExceptionHandler.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/controlleradvice/ControllerExceptionHandlerTest.java
Fixing the sort order on question responses where multiple errors may appear on the screen at once. Previously these were just displayed in whatever order the code encountered the validation error but now they appear in the same order as the form. 
[GAP-1596](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-1596)
Added a couple of methods to the controller exception handler to sort messages before they are returned back through the API
[GAP-1596]: …
> GAP-1596: properly sort error messages from back end

- src/main/java/gov/cabinetoffice/gap/applybackend/dto/api/SchemeMandatoryQuestionApplicationFormInfosDto.java
- src/main/java/gov/cabinetoffice/gap/applybackend/exception/AdvertNotPublishedException.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicationService.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsController.java
- src/main/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeController.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/service/GrantApplicationServiceTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantMandatoryQuestionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/applybackend/web/GrantSchemeControllerTest.java
> GAP-2537:add logic to handle application with no adverts
